In [54]:
import math
math.pi
print(math.sin(90))

0.8939966636005579


In [55]:
import math as ma
#to import with another name
#the same package can be imported twice with two different names and both work

In [56]:
ma.log(100)

4.605170185988092

In [57]:
ma.log(100,10)

2.0

In [58]:
math.log(100,10)

2.0

In [59]:
import numpy as np
cf=[50,100,120,150,200,300]
#we can create arrays
cf_a=np.array(cf)

In [60]:
cf_a

array([ 50, 100, 120, 150, 200, 300])

In [61]:
#cf is a list and cf_a is an array. Lists do not allow operations like multiplying all the elements in the list 
cf*1.2

TypeError: can't multiply sequence by non-int of type 'float'

In [62]:
#arrays allow such operatiosn and when doing it, all the elemnts of the array are multiplied
cf_a*1.2

array([  60.,  120.,  144.,  180.,  240.,  360.])

In [63]:
#also it is possible to sum 2 arrays as long as they have the same dimensions
cf_add=np.array([15,3,-12,15,2,25])
new_a=cf_a+cf_add

In [64]:
new_a

array([ 65, 103, 108, 165, 202, 325])

In [65]:
#attribute of array is dtype to know the type of the array
new_a.dtype

dtype('int32')

In [66]:
#arrays can hold only one type of data. If we put numbers and strings in an array, all will be taken as string
string_a=np.array(["Hola",3,-12,15,2,25,True])
string_a.dtype

dtype('<U4')

In [67]:
string_a

array(['Hola', '3', '-12', '15', '2', '25', 'True'], 
      dtype='<U4')

In [68]:
#if we mix numbers and True/False then it will be processed as 1,0 respectively and all the arrya will be integer
string_a2=np.array([3,-12,15,2,25,True])
string_a2.dtype

dtype('int32')

In [69]:
string_a2

array([  3, -12,  15,   2,  25,   1])

In [70]:
#it one of the numbers is float, then the whole array is float
string_a3=np.array([3.1,-12,15,2,25,True])
string_a3.dtype

dtype('float64')

In [71]:
#indexes can be used as in lists
cf_a[0]

50

In [72]:
cf_a[-1]

300

In [73]:
#all elements except the last one
cf_a[0:-1]

array([ 50, 100, 120, 150, 200])

In [74]:
#reverse
cf_a[::-1]

array([300, 200, 150, 120, 100,  50])

In [75]:
#also multiplication and division are allowed
#lets calculate the NPV of the following cashflows.
cf=np.array([-200,20,50,70,100,50])
r=0.06
f=1+r
n=np.array([0,1,2,3,4,5])


In [76]:
pv_array=cf/f**n

In [77]:
#the sum of all present cashflows can be calculated with .sum
NPV=pv_array.sum()

In [78]:
NPV

38.713371308379912

In [79]:
#arrays are mutable like lists
cf1=np.array([50,100,120,150,200,300])
cf2=cf1
cf1[0]=100
print(cf1, cf2,)

[100 100 120 150 200 300] [100 100 120 150 200 300]


In [80]:
#to avoid this we can use .copy()
cf1=np.array([50,100,120,150,200,300])
cf2=cf1.copy()
cf1[0]=100
print(cf1, cf2,)

[100 100 120 150 200 300] [ 50 100 120 150 200 300]
